### ISSUE TITLE
2 files will remain

### ISSUE THREAD

**Issue by muhinyia** [DeKUT-DSAIL/dsail-tech4wildlife#1]
You may need to copy file after the if statement (after creating the directory) as no file is copied in the first loop.

**Comment by kaburia** [comment]
def split_data(image_dir, label_df, value):
    '''
    Split and organize image data into train, test, or validation directories based on given labels.

    This function takes in image data and corresponding label information in the form of a DataFrame,
    and organizes the images into separate directories for training, testing, or validation purposes.

    Args:
    -----------------
    - image_dir (str): Path to the directory containing the image files.
    - label_df (pandas.DataFrame): DataFrame containing label information, including filenames and species labels.
    - The DataFrame must have a "Species" column.
        value (str): Type of data split, either 'train', 'test', or 'validation'.

    Returns:
    -----------------
        None

    Raises:
    -----------------
        ValueError: If label_df is not a pandas DataFrame or if it doesn't contain a "Species" column.
    '''

    if not isinstance(label_df, pd.DataFrame):
        raise ValueError("The 'label_df' argument must be a pandas DataFrame.")

    if "Species" not in label_df.columns:
        raise ValueError("The 'label_df' DataFrame must contain a 'Species' column.")

    for ind, row in label_df.iterrows():
        # Check if the target directory exists, if not create it
        if not os.path.exists(value):
            os.mkdir(value)
            os.mkdir(f'{value}/{row["Species"]}')
            shutil.move(f'{image_dir}/{row["filename"]}', f'{value}/{row["Species"]}')
        else:
            # If the target species directory doesn't exist, create it
            if not os.path.exists(f'{value}/{row["Species"]}'):
                os.mkdir(f'{value}/{row["Species"]}')
                shutil.move(f'{image_dir}/{row["filename"]}', f'{value}/{row["Species"]}')
            else:
                # Copy the image file to the corresponding species directory
                shutil.move(f'{image_dir}/{row["filename"]}', f'{value}/{row["Species"]}')
